# Generated by Django 2.0.1 on 2018-01-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back']},
        ),
    ]
